### ISSUE TITLE
Add support for more browsers using Polymer's platform polyfills

### ISSUE THREAD

**Issue by k4b7** [mathiasbynens/math-tex#1]
The Polymer project has some excellent polyfills that could be used to provide broader support.
https://www.polymer-project.org/docs/start/platform.html

**Comment by mathiasbynens** [comment]
This project is a vanilla web component _by design_. I intentionally did not want to introduce any dependencies that are not needed by browsers that fully support the web components stack.

If there’s any interest I’d be happy to set up a separate repository for a version that depends on Polymer, but at some point in the future that will become obsolete anyhow.
